<script type="text/javascript" src="js/jquery-3.4.1.min.js"></script>
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1/i18n/jquery.ui.datepicker-ja.min.js"></script> -->
<script type="text/javascript" src="plugin/cookie/cookie.js"></script>
<script type="text/javascript" src="plugin/moment.js/moment.js"></script>
<!-- <script src="https://cdn.jsdelivr.net/npm/promise-polyfill@7.1.0/dist/promise.min.js"></script> -->
<!-- <script type="text/javascript" src="plugin/sweet-alert/sweetalert2.min.js"></script>
<script type="text/javascript" src="plugin/iziModal-master/js/iziModal.js"></script> -->
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<!-- <script type="text/javascript" src="plugin/tablesorter/jquery.tablesorter.js"></script>
<script type="text/javascript" src="plugin/tablesorter/jquery.tablesorter.widgets.js"></script>
<script type="text/javascript" src="plugin/tablesorter/widget-scroller.js"></script>
<script type="text/javascript" src="/plugin/jalert/jquery.alerts.js"></script>
<script type="text/javascript" src="/plugin/jquery.smSearchInputSelector/jquery.smSearchInputSelector.js"></script> -->
<script type="text/javascript" src="js/common.js?vs=<?php echo TIMESTAMP ?>"></script>