<link rel="stylesheet" type="text/css" href="css/reset.css?vs=<?php echo TIMESTAMP ?>">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css"/>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.1/css/all.css"/>
<link rel="stylesheet" type="text/css" href="plugin/sweet-alert/css/sweetalert2.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/themes/base/jquery-ui.min.css">
<link rel="stylesheet" href="plugin/tablesorter/theme.jui.css" />
<link rel="stylesheet" type="text/css" href="plugin/iziModal-master/css/iziModal.css">
<link rel="stylesheet" href="/plugin/jalert/jquery.alerts.css" />
<link rel="stylesheet" href="/plugin/jquery.smSearchInputSelector/jquery.smSearchInputSelector.css" />